<?php

/**
 * Catálogo NAV / ACCIONES del Command Palette (11F-2).
 * Solo rutas reales; el filtrado por permiso ocurre en GlobalSearchService.
 *
 * @return array{
 *   navigation: list<array{label: string, keywords: list<string>, route: string, params?: array<string, mixed>, permission: string|list<string>, subtitle?: string}>,
 *   actions: list<array{label: string, keywords: list<string>, route: string, params?: array<string, mixed>, permission: string|list<string>, subtitle?: string}>,
 * }
 */
return [
    'navigation' => [
        [
            'label' => 'Tablero operativo',
            'keywords' => ['dashboard', 'tablero', 'inicio', 'operativo'],
            'route' => 'dashboard.operations',
            'permission' => 'dashboard.view',
            'subtitle' => 'Inicio',
        ],
        [
            'label' => 'Tablero de gestión',
            'keywords' => ['dashboard', 'gestion', 'gestión', 'kpi', 'ranking'],
            'route' => 'dashboard.management',
            'permission' => 'dashboard.view',
            'subtitle' => 'Inicio',
        ],
        [
            'label' => 'Cuentas financieras',
            'keywords' => ['caja', 'banco', 'billetera', 'liquidez'],
            'route' => 'accounts.index',
            'permission' => 'accounts.view',
            'subtitle' => 'Finanzas',
        ],
        [
            'label' => 'Movimientos',
            'keywords' => ['ingresos', 'egresos', 'transferencias'],
            'route' => 'movements.index',
            'permission' => 'movements.view',
            'subtitle' => 'Finanzas',
        ],
        [
            'label' => 'Cotizaciones',
            'keywords' => ['tipo de cambio', 'dolar', 'dólar', 'exchange'],
            'route' => 'exchange-rates.index',
            'permission' => 'exchange_rates.view',
            'subtitle' => 'Finanzas',
        ],
        [
            'label' => 'Clientes',
            'keywords' => ['cliente', 'cc', 'cuenta corriente'],
            'route' => 'clients.index',
            'permission' => 'clients.view',
            'subtitle' => 'Maestros',
        ],
        [
            'label' => 'Cuentas corrientes de clientes',
            'keywords' => ['cc', 'ranking', 'deuda', 'cobrar', 'cuenta corriente'],
            'route' => 'clients.current-accounts',
            'permission' => 'clients.view',
            'subtitle' => 'Clientes',
        ],
        [
            'label' => 'Proveedores',
            'keywords' => ['proveedor', 'compra'],
            'route' => 'suppliers.index',
            'permission' => 'suppliers.view',
            'subtitle' => 'Maestros',
        ],
        [
            'label' => 'Productos',
            'keywords' => ['sku', 'catálogo', 'catalogo'],
            'route' => 'products.index',
            'permission' => 'products.view',
            'subtitle' => 'Maestros',
        ],
        [
            'label' => 'Tipos de equipo',
            'keywords' => ['plantilla', 'equipo'],
            'route' => 'equipment.types.index',
            'permission' => 'equipment.view',
            'subtitle' => 'Maestros',
        ],
        [
            'label' => 'Plan de cuentas',
            'keywords' => ['categoria', 'categoría', 'subcategoria', 'contable', 'chart', 'ingresos', 'egresos'],
            'route' => 'chart-accounts.index',
            'permission' => 'categories.view',
            'subtitle' => 'Maestros',
        ],
        [
            'label' => 'Clasificar movimientos',
            'keywords' => ['sin clasificar', 'imputacion', 'mapeo'],
            'route' => 'chart-accounts.classify',
            'permission' => 'categories.view',
            'subtitle' => 'Maestros',
        ],
        [
            'label' => 'Presupuestos',
            'keywords' => ['cotizacion', 'cotización', 'oferta'],
            'route' => 'quotations.index',
            'permission' => 'quotations.view',
            'subtitle' => 'Comercial',
        ],
        [
            'label' => 'Ventas',
            'keywords' => ['factura', 'comercial'],
            'route' => 'sales.index',
            'permission' => 'sales.view',
            'subtitle' => 'Comercial',
        ],
        [
            'label' => 'Abonos',
            'keywords' => ['suscripcion', 'suscripción', 'recurrente'],
            'route' => 'subscriptions.index',
            'permission' => 'subscriptions.view',
            'subtitle' => 'Comercial',
        ],
        [
            'label' => 'Cargos al cliente',
            'keywords' => ['cargo', 'deuda', 'cc in'],
            'route' => 'charges.index',
            'permission' => 'charges.view',
            'subtitle' => 'Comercial',
        ],
        [
            'label' => 'Cobros',
            'keywords' => ['cobro', 'recibo', 'pago cliente', 'patagonia'],
            'route' => 'receipts.index',
            'permission' => 'receipts.view',
            'subtitle' => 'Comercial',
        ],
        [
            'label' => 'Operaciones sin comprobante',
            'keywords' => ['comprobante', 'documental', 'factura pendiente'],
            'route' => 'documental.pending',
            'permission' => 'charges.view',
            'subtitle' => 'Comercial',
        ],
        [
            'label' => 'Órdenes de trabajo',
            'keywords' => ['ot', 'reparacion', 'reparación', 'servicio'],
            'route' => 'work-orders.index',
            'permission' => 'work_orders.view',
            'subtitle' => 'Operaciones',
        ],
        [
            'label' => 'Productos',
            'keywords' => ['sku', 'catálogo', 'catalogo'],
            'route' => 'products.index',
            'permission' => 'products.view',
            'subtitle' => 'Inventario',
        ],
        [
            'label' => 'Equipos',
            'keywords' => ['serial', 'armado'],
            'route' => 'equipment.index',
            'permission' => 'equipment.view',
            'subtitle' => 'Inventario',
        ],
        [
            'label' => 'Stock / Unidades',
            'keywords' => ['inventario', 'existencias', 'fifo', 'unidad'],
            'route' => 'stock.index',
            'permission' => 'stock.view',
            'subtitle' => 'Inventario',
        ],
        [
            'label' => 'Compras',
            'keywords' => ['mercaderia', 'mercadería', 'proveedor'],
            'route' => 'purchases.index',
            'permission' => 'purchases.view',
            'subtitle' => 'Inventario',
        ],
        [
            'label' => 'Reportes',
            'keywords' => ['exportar', 'consulta'],
            'route' => 'reports.index',
            'permission' => 'reports.view',
            'subtitle' => 'Reportes',
        ],
        [
            'label' => 'Importaciones',
            'keywords' => ['historico', 'histórico', 'carga'],
            'route' => 'imports.index',
            'permission' => 'imports.view',
            'subtitle' => 'Reportes',
        ],
        [
            'label' => 'Usuarios',
            'keywords' => ['admin', 'acceso'],
            'route' => 'users.index',
            'permission' => 'users.view',
            'subtitle' => 'Administración',
        ],
        [
            'label' => 'Permisos',
            'keywords' => ['roles', 'admin', 'matriz'],
            'route' => 'permissions.index',
            'permission' => 'permissions.view',
            'subtitle' => 'Administración',
        ],
        [
            'label' => 'Configuración',
            'keywords' => ['settings', 'ajustes'],
            'route' => 'settings.edit',
            'permission' => 'settings.view',
            'subtitle' => 'Administración',
        ],
        [
            'label' => 'Auditoría',
            'keywords' => ['audit', 'auditoria', 'log', 'historial', 'admin'],
            'route' => 'audit.index',
            'permission' => 'audit.view',
            'subtitle' => 'Administración',
        ],
    ],

    'actions' => [
        [
            'label' => 'Cargar movimiento',
            'keywords' => ['ingreso', 'egreso', 'nuevo movimiento', 'cargar'],
            'route' => 'movements.quick',
            'permission' => 'movements.create',
            'subtitle' => 'Acción rápida',
        ],
        [
            'label' => 'Nuevo cliente',
            'keywords' => ['crear cliente', 'alta cliente'],
            'route' => 'clients.create',
            'permission' => 'clients.create',
            'subtitle' => 'Clientes',
        ],
        [
            'label' => 'Nuevo proveedor',
            'keywords' => ['crear proveedor', 'alta proveedor'],
            'route' => 'suppliers.create',
            'permission' => 'suppliers.create',
            'subtitle' => 'Proveedores',
        ],
        [
            'label' => 'Nuevo producto',
            'keywords' => ['crear producto', 'alta producto'],
            'route' => 'products.create',
            'permission' => 'products.create',
            'subtitle' => 'Productos',
        ],
        [
            'label' => 'Nueva compra',
            'keywords' => ['crear compra', 'ingresar mercaderia'],
            'route' => 'purchases.create',
            'permission' => 'purchases.create',
            'subtitle' => 'Compras',
        ],
        [
            'label' => 'Nuevo presupuesto',
            'keywords' => ['crear presupuesto', 'cotizar'],
            'route' => 'quotations.create',
            'permission' => 'quotations.create',
            'subtitle' => 'Comercial',
        ],
        [
            'label' => 'Nueva venta',
            'keywords' => ['crear venta', 'facturar'],
            'route' => 'sales.create',
            'permission' => 'sales.create',
            'subtitle' => 'Comercial',
        ],
        [
            'label' => 'Nueva orden de trabajo',
            'keywords' => ['crear ot', 'nueva ot', 'reparar'],
            'route' => 'work-orders.create',
            'permission' => 'work_orders.create',
            'subtitle' => 'Operaciones',
        ],
        [
            'label' => 'Nuevo equipo',
            'keywords' => ['crear equipo', 'armar'],
            'route' => 'equipment.create',
            'permission' => 'equipment.create',
            'subtitle' => 'Operaciones',
        ],
        [
            'label' => 'Nuevo abono',
            'keywords' => ['crear abono', 'suscripcion'],
            'route' => 'subscriptions.create',
            'permission' => 'subscriptions.create',
            'subtitle' => 'Comercial',
        ],
        [
            'label' => 'Nueva cuenta financiera',
            'keywords' => ['crear cuenta', 'caja', 'banco'],
            'route' => 'accounts.create',
            'permission' => 'accounts.create',
            'subtitle' => 'Finanzas',
        ],
        [
            'label' => 'Nuevo usuario',
            'keywords' => ['crear usuario', 'alta usuario', 'admin'],
            'route' => 'users.create',
            'permission' => 'users.create',
            'subtitle' => 'Administración',
        ],
    ],
];
